import Head from "next/head";
import styles from "../styles/Home.module.css";
import Blogs from "./blog";
import Link from "next/link";
import React, { useState } from "react";

export default function Home({}) {
  const [cari, setCari] = useState("");
  const [tampung, setTampung] = useState([]);
  const [loading, setLoading] = useState(false);
  function handleClick() {
    setLoading(true);
    fetch(`${process.env.NEXT_PUBLIC_KEY}` + `${cari}`)
      .then(res => res.json())
      .then(data => {
        setLoading(false);
        setTampung(data.Search);
        console.log(data.Search);
      })
      .catch(err => console.log(err));
  }
  function Tampiltampung(tampung) {
    return tampung.map(movie => <div>{movie.Title}</div>);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Blogs />
        <Link href="route">
          <a>Route</a>
        </Link>
        <input type="text" onChange={e => setCari(e.target.value)} />
        <button onClick={handleClick}>Click</button>
        <br />
        {loading ? "Loading.." : Tampiltampung(tampung)}
      </div>
    </div>
  );
}
